import { useContext, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, ChevronRight, FileText, Home, LockKeyhole, Map as MapIcon, MapPin, Users, XCircle } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AuthContext } from '../context/AuthContext';
import Layout from '../components/Layout';
import MapaDenuncia from '../components/MapaLeaflet';
import { ActionCard, MetricCard } from '../components/DashboardCards';

const API = import.meta.env.VITE_API_URL;
const CATEGORY_NAMES = { 2: 'Alagamento', 3: 'Assalto/Roubo', 5: 'Iluminação', 6: 'Buraco na via', 7: 'Desabamento', 8: 'Outro' };
const COLORS = ['#6c2bd9', '#14956b', '#8b5cf6', '#d68b18', '#c44747'];
const STATUS = { aprovado: ['Aprovado', 'var(--color-primary)'], pendente: ['Em análise', 'var(--color-warning)'], rejeitado: ['Rejeitado', 'var(--color-danger)'], resolvida: ['Resolvido', 'var(--color-success)'] };
const norm = (value) => String(value || '').trim().toLowerCase();
const number = (value) => Number(value?.total ?? value ?? 0) || 0;
const cityFromMessage = (message) => String(message || '').match(/cidade\s+(.+?)(?:\.|$)/i)?.[1]?.trim() || '';
const categoryName = (report) => report.category || report.category_name || CATEGORY_NAMES[report.category_id] || `Categoria #${report.category_id || '—'}`;
const neighborhoodName = (report) => report.neighborhood_name || report.neighborhoodName || report.neighborhood?.name || report.neighborhood || (report.neighborhood_id ? `Bairro #${report.neighborhood_id}` : 'Bairro não informado');
const field = 'h-10 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-muted)] px-3 text-sm text-[var(--color-ink)]';

function Empty({ children }) { return <p className="grid h-56 place-items-center text-sm text-[var(--color-muted)]">{children}</p>; }
function RecentReports({ reports }) { const navigate = useNavigate(); return <section className="urban-surface overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-[var(--color-border-subtle)] px-4 py-4"><div><h2 className="font-bold text-[var(--color-ink)]">Relatos recentes</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Últimos registros da cidade.</p></div><button type="button" onClick={() => navigate('/Report')} className="text-xs font-bold text-[var(--color-primary)] hover:underline">Ver todos</button></div>{reports.length ? <div className="divide-y divide-[var(--color-border-subtle)]">{reports.map((report) => { const meta = STATUS[norm(report.status)] || [report.status || 'Relato', 'var(--color-muted)']; return <button type="button" key={report.id} onClick={() => navigate(`/report/${report.id}`)} className="flex w-full min-w-0 items-center gap-3 px-4 py-3 text-left hover:bg-[var(--color-surface-muted)]"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[var(--color-soft)]" style={{ color: meta[1] }}><FileText size={16} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[var(--color-ink)]">{report.reportTitle || 'Relato sem título'}</strong><small className="mt-0.5 block truncate text-xs text-[var(--color-muted)]">{meta[0]} · {report.address || 'Localização não informada'}</small></span><ChevronRight size={16} className="shrink-0 text-[var(--color-muted)]" /></button>; })}</div> : <div className="px-4 py-12 text-center"><FileText className="mx-auto text-[var(--color-muted)]" size={24} /><p className="mt-3 text-sm font-bold text-[var(--color-ink)]">Ainda não há relatos</p><p className="mt-1 text-xs text-[var(--color-muted)]">Os novos registros aparecerão aqui.</p></div>}</section>; }
function Restricted() { return <Layout><main className="grid min-h-[70vh] place-items-center p-6"><div className="max-w-sm text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[var(--color-danger-tint)] text-[var(--color-danger)]"><LockKeyhole /></span><h1 className="mt-4 text-xl font-bold text-[var(--color-ink)]">Acesso restrito</h1><p className="mt-1 text-sm text-[var(--color-muted)]">Este painel é exclusivo para gestores municipais.</p></div></main></Layout>; }

export default function DashboardMunicipal() {
  const { user, token } = useContext(AuthContext); const navigate = useNavigate();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [period, setPeriod] = useState('all'); const [category, setCategory] = useState('all'); const [neighborhood, setNeighborhood] = useState('all'); const [status, setStatus] = useState('all');
  const hasAccess = String(user?.role) === '7';
  useEffect(() => { if (!hasAccess) return; fetch(`${API}/dashboard`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload?.message || 'Não foi possível carregar o painel municipal.'); setData(payload); }).catch((requestError) => setError(requestError.message || 'Não foi possível carregar o painel municipal.')).finally(() => setLoading(false)); }, [hasAccess, token]);

  // GET /dashboard is intentionally the sole source for role 7; its AllReports payload is server-scoped to the municipality.
  const municipalReports = Array.isArray(data?.AllReports) ? data.AllReports : [];
  const cityName = cityFromMessage(data?.message);
  const analytics = useMemo(() => {
    const cutoff = period === '30' ? Date.now() - 30 * 86400000 : period === '90' ? Date.now() - 90 * 86400000 : 0;
    const reports = municipalReports.filter((report) => { const date = new Date(report.created_at || report.updated_at || 0).getTime(); return (!cutoff || date >= cutoff) && (category === 'all' || String(report.category_id) === category) && (neighborhood === 'all' || String(report.neighborhood_id) === neighborhood) && (status === 'all' || norm(report.status) === status); });
    const group = (label) => [...reports.reduce((map, report) => { const name = label(report); map.set(name, (map.get(name) || 0) + 1); return map; }, new Map()).entries()].map(([name, total]) => ({ name, total })).sort((a, b) => b.total - a.total);
    const trend = [...reports.reduce((map, report) => { const date = new Date(report.created_at || report.updated_at); if (Number.isNaN(date.getTime())) return map; const name = date.toLocaleDateString('pt-BR', { month: 'short', year: '2-digit' }); const point = map.get(name) || { name, received: 0, approved: 0, timestamp: date.getTime() }; point.received += 1; if (['aprovado', 'resolvida'].includes(norm(report.status))) point.approved += 1; map.set(name, point); return map; }, new Map()).values()].sort((a, b) => a.timestamp - b.timestamp).slice(-6);
    const options = (id, label) => [...new Map(municipalReports.filter((report) => report[id] !== null && report[id] !== undefined && report[id] !== '').map((report) => [String(report[id]), label(report)])).entries()].map(([value, label]) => ({ value, label }));
    return { reports, trend, categories: group(categoryName), neighborhoods: group(neighborhoodName), categoryOptions: options('category_id', categoryName), neighborhoodOptions: options('neighborhood_id', neighborhoodName), recent: [...reports].sort((a, b) => new Date(b.updated_at || b.created_at || 0) - new Date(a.updated_at || a.created_at || 0)).slice(0, 5) };
  }, [municipalReports, period, category, neighborhood, status]);
  const counts = useMemo(() => ['aprovado', 'pendente', 'rejeitado'].reduce((result, key) => ({ ...result, [key]: municipalReports.filter((report) => norm(report.status) === key).length }), {}), [municipalReports]);
  const downloadCsv = () => { const rows = [['ID', 'Título', 'Descrição', 'Categoria', 'Bairro', 'Endereço', 'Status', 'Data de criação', 'Latitude', 'Longitude'], ...analytics.reports.map((report) => [report.id || '', report.reportTitle || '', report.description || '', categoryName(report), neighborhoodName(report), report.address || '', report.status || '', report.created_at || report.updated_at || '', report.latitude ?? '', report.longitude ?? ''])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(';')).join('\n'); const slug = (cityName || 'municipio').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '-').replace(/(^-|-$)/g, '').toLowerCase(); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = `relatorio-${slug || 'municipio'}-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  if (!hasAccess) return <Restricted />;
  if (loading) return <Layout><main className="grid min-h-[70vh] place-items-center p-6 text-sm text-[var(--color-muted)]">Carregando dados do município…</main></Layout>;
  if (error) return <Layout><main className="p-4 md:p-8"><div role="alert" className="rounded-xl border border-[var(--color-danger)] bg-[var(--color-danger-tint)] p-4 text-sm text-[var(--color-danger)]">{error}</div></main></Layout>;
  return <Layout><main className="w-full px-4 py-4 md:px-8 md:py-6"><header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="urban-eyebrow">Gestão municipal</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-[var(--color-ink)]">{cityName || 'Painel municipal'}</h1><p className="mt-1 text-sm text-[var(--color-muted)]">Acompanhe os relatos e a situação da cidade.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[var(--color-success-tint)] px-3 py-1.5 text-xs font-bold text-[var(--color-success)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--color-success)]" /> Dados atuais</span></header>
    <section aria-label="Indicadores municipais" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard icon={FileText} label="Relatos registrados" value={municipalReports.length} description="Todos os status" tone="var(--color-primary)" /><MetricCard icon={CheckCircle2} label="Aprovados" value={number(data?.TotalReports)} description="Relatos publicados" tone="var(--color-success)" /><MetricCard icon={AlertTriangle} label="Em análise" value={counts.pendente} description="Aguardando decisão" tone="var(--color-warning)" /><MetricCard icon={XCircle} label="Rejeitados" value={counts.rejeitado} description="Relatos não publicados" tone="var(--color-danger)" /><MetricCard icon={Users} label="População cadastrada" value={number(data?.TotalPopulationCity)} description="Usuários vinculados à cidade" tone="var(--color-primary)" /></section>
    <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.75fr)]"><section className="urban-surface min-h-[300px] p-4 md:p-5"><h2 className="font-bold text-[var(--color-ink)]">Tendência de relatos</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Relatos recebidos e aprovados no período selecionado.</p>{analytics.trend.length ? <div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.trend}><CartesianGrid stroke="var(--color-border-subtle)" strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fill: 'var(--color-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'var(--color-muted)', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip /><Legend wrapperStyle={{ fontSize: 12 }} /><Area type="monotone" dataKey="received" name="Recebidos" stroke="#6c2bd9" fill="#6c2bd9" fillOpacity={0.16} strokeWidth={2} /><Area type="monotone" dataKey="approved" name="Aprovados" stroke="#14956b" fill="#14956b" fillOpacity={0.1} strokeWidth={2} /></AreaChart></ResponsiveContainer></div> : <Empty>Sem datas suficientes para exibir a tendência.</Empty>}</section><section className="urban-surface min-h-[300px] p-4 md:p-5"><h2 className="font-bold text-[var(--color-ink)]">Tipos de relatos</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Distribuição por categoria.</p>{analytics.categories.length ? <div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.categories.slice(0, 5)} dataKey="total" nameKey="name" innerRadius={52} outerRadius={82} paddingAngle={3}>{analytics.categories.slice(0, 5).map((entry, index) => <Cell key={entry.name} fill={COLORS[index]} />)}</Pie><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /></PieChart></ResponsiveContainer></div> : <Empty>Sem categorias disponíveis.</Empty>}</section></section>
    <section className="urban-surface mt-4 min-h-[250px] p-4 md:p-5"><h2 className="font-bold text-[var(--color-ink)]">Relatos por bairro</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Distribuição dos relatos registrados na cidade.</p>{analytics.neighborhoods.length ? <div className="mt-4 h-48"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.neighborhoods.slice(0, 7)} layout="vertical" margin={{ left: 20 }}><CartesianGrid stroke="var(--color-border-subtle)" horizontal={false} /><XAxis type="number" allowDecimals={false} tick={{ fill: 'var(--color-muted)', fontSize: 11 }} /><YAxis type="category" dataKey="name" width={110} tick={{ fill: 'var(--color-muted)', fontSize: 11 }} /><Tooltip /><Bar dataKey="total" name="Relatos" fill="#6c2bd9" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div> : <p className="grid h-48 place-items-center text-sm text-[var(--color-muted)]">Sem bairros disponíveis.</p>}</section>
    <section className="urban-surface mt-4 p-4 md:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-bold text-[var(--color-ink)]">Relatórios municipais</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Filtre os relatos da cidade e exporte os dados disponíveis.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={downloadCsv} className="rounded-lg bg-[var(--color-primary)] px-3 py-2 text-xs font-bold text-white">Baixar CSV</button><button type="button" disabled className="cursor-not-allowed rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs font-bold text-[var(--color-muted)]">PDF · Em breve</button></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><select value={period} onChange={(event) => setPeriod(event.target.value)} className={field}><option value="all">Todo o período</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select><select value={category} onChange={(event) => setCategory(event.target.value)} className={field}><option value="all">Todas as categorias</option>{analytics.categoryOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={neighborhood} onChange={(event) => setNeighborhood(event.target.value)} className={field}><option value="all">Todos os bairros</option>{analytics.neighborhoodOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className={field}><option value="all">Todos os status</option><option value="pendente">Pendentes</option><option value="aprovado">Aprovados</option><option value="rejeitado">Rejeitados</option><option value="resolvida">Resolvidos</option></select></div></section>
    <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(320px,.7fr)]"><section className="urban-surface overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-[var(--color-border-subtle)] px-4 py-4"><div><h2 className="font-bold text-[var(--color-ink)]">Mapa dos problemas</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Atualizações da cidade.</p></div><button type="button" onClick={() => navigate('/mapa')} className="text-[var(--color-primary)]" aria-label="Abrir mapa"><MapIcon size={18} /></button></div><div className="h-[300px] p-2 md:h-[380px]"><MapaDenuncia reports={municipalReports} showCityPicker={false} interactive={false} /></div></section><RecentReports reports={analytics.recent} /></section>
    <section className="urban-surface mt-5 p-4"><h2 className="font-bold text-[var(--color-ink)]">Ações rápidas</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Acesse recursos disponíveis para a gestão municipal.</p><div className="mt-4 grid gap-2 md:grid-cols-3"><ActionCard icon={MapPin} title="Abrir mapa" description="Visualizar relatos no território" onClick={() => navigate('/mapa')} /><ActionCard icon={FileText} title="Ver relatos da cidade" description="Acompanhar registros publicados" onClick={() => navigate('/Report')} /><ActionCard icon={Home} title="Ir para Início" description="Voltar à página inicial" onClick={() => navigate('/')} /></div></section>
  </main></Layout>;
}
