import { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import Layout from './Layout';
import { Check, MapPin, Search, X } from 'lucide-react';

export default function PendingReports() {
  const { token } = useContext(AuthContext); const [reports, setReports] = useState([]); const [filter, setFilter] = useState('');
  useEffect(() => { fetch(`${import.meta.env.VITE_API_URL}/reportPending`).then((res) => res.json()).then((data) => setReports(data.data || [])).catch((err) => console.error(err)); }, []);
  const handleAction = async (id, action) => { try { const res = await fetch(`${import.meta.env.VITE_API_URL}/${action}Report/${id}`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (!res.ok) { const d = await res.json(); alert(d.message || d.error || 'Erro na ação.'); return; } setReports((prev) => prev.filter((r) => r.id !== id)); } catch (err) { console.error(err); } };
  const filtered = reports.filter((r) => r.reportTitle.toLowerCase().includes(filter.toLowerCase()));
  return <Layout><main className="mx-auto max-w-[1500px] px-4 py-5 md:px-8"><header className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="urban-eyebrow">Fila de moderação</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Denúncias pendentes</h1><p className="mt-1 text-sm text-[#71839a]">Revise os relatos antes de publicar para a comunidade.</p></div><span className="w-fit rounded-full bg-[#fff7e8] px-3 py-1.5 text-xs font-bold text-[#a86d08]">{reports.length} aguardando análise</span></header><div className="urban-surface mb-4 flex items-center gap-2 px-3 py-2 sm:max-w-md"><Search size={17} className="text-[#8a9aad]"/><input value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="Buscar por título" className="h-8 flex-1 bg-transparent text-sm outline-none placeholder:text-[#a1adbc]"/></div>{filtered.length === 0 ? <div className="urban-surface py-16 text-center"><p className="font-bold">Nenhuma denúncia pendente</p><p className="mt-1 text-sm text-[#71839a]">A fila está limpa por enquanto.</p></div> : <div className="urban-surface divide-y divide-[#e8edf3] overflow-hidden">{filtered.map((report) => <article key={report.id} className="grid gap-4 p-4 md:grid-cols-[96px_1fr_auto] md:items-center"><img src={report.image ? `${import.meta.env.VITE_API_URL}/uploads/${report.image}` : '/placeholder.png'} alt="" className="h-20 w-24 rounded-lg object-cover"/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-[#142f52]">{report.reportTitle}</h2><span className="rounded-full bg-[#fff7e8] px-2 py-1 text-[10px] font-bold text-[#a86d08]">Em análise</span></div><p className="mt-1 line-clamp-2 text-sm text-[#536981]">{report.description}</p><p className="mt-2 flex items-center gap-1 text-xs text-[#91a0b3]"><MapPin size={13}/>{report.address || 'Localização não informada'}</p></div><div className="flex gap-2 md:flex-col"><button onClick={() => handleAction(report.id, 'approve')} className="inline-flex min-h-9 flex-1 items-center justify-center gap-1.5 rounded-lg bg-[#eaf8f2] px-3 text-xs font-bold text-[#16835f] hover:bg-[#d8f1e7]"><Check size={15}/> Aprovar</button><button onClick={() => handleAction(report.id, 'decline')} className="inline-flex min-h-9 flex-1 items-center justify-center gap-1.5 rounded-lg bg-[#fff1f1] px-3 text-xs font-bold text-[#c44747] hover:bg-[#fbe1e1]"><X size={15}/> Rejeitar</button></div></article>)}</div>}</main></Layout>;
}
