import { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import Layout from './Layout';
import AdminBackLink from './AdminBackLink';
import { Check, MapPin, Search, X } from 'lucide-react';

export default function PendingReports() {
  const { token } = useContext(AuthContext); const [reports, setReports] = useState([]); const [filter, setFilter] = useState('');
  useEffect(() => { fetch(`${import.meta.env.VITE_API_URL}/reportPending`).then((res) => res.json()).then((data) => setReports(data.data || [])).catch((err) => console.error(err)); }, []);
  const handleAction = async (id, action) => { try { const res = await fetch(`${import.meta.env.VITE_API_URL}/${action}Report/${id}`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (!res.ok) { const data = await res.json(); alert(data.message || data.error || 'Erro na ação.'); return; } setReports((previous) => previous.filter((report) => report.id !== id)); } catch (err) { console.error(err); } };
  const filtered = reports.filter((report) => report.reportTitle.toLowerCase().includes(filter.toLowerCase()));
  return <Layout><main className="mx-auto max-w-[1500px] px-4 py-5 md:px-8"><AdminBackLink /><header className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="urban-eyebrow">Fila de moderação</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Denúncias pendentes</h1><p className="mt-1 text-sm text-[var(--color-muted)]">Revise os relatos antes de publicar para a comunidade.</p></div><span className="w-fit rounded-full bg-[var(--color-warning-tint)] px-3 py-1.5 text-xs font-bold text-[var(--color-warning)]">{reports.length} aguardando análise</span></header><div className="urban-surface mb-4 flex items-center gap-2 px-3 py-2 sm:max-w-md"><Search size={17} className="text-[var(--color-muted)]"/><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Buscar por título" className="h-8 flex-1 bg-transparent text-sm outline-none placeholder:text-[var(--color-muted)]"/></div>{filtered.length === 0 ? <div className="urban-surface py-16 text-center"><p className="font-bold">Nenhuma denúncia pendente</p><p className="mt-1 text-sm text-[var(--color-muted)]">A fila está limpa por enquanto.</p></div> : <div className="urban-surface divide-y divide-[var(--color-border-subtle)] overflow-hidden">{filtered.map((report) => <article key={report.id} className="grid gap-4 p-4 md:grid-cols-[96px_1fr_auto] md:items-center"><img src={report.image ? `${import.meta.env.VITE_API_URL}/uploads/${report.image}` : '/placeholder.png'} alt="" className="h-20 w-24 rounded-lg object-cover"/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-[var(--color-ink)]">{report.reportTitle}</h2><span className="rounded-full bg-[var(--color-warning-tint)] px-2 py-1 text-[10px] font-bold text-[var(--color-warning)]">Em análise</span></div><p className="mt-1 line-clamp-2 text-sm text-[var(--color-muted)]">{report.description}</p><p className="mt-2 flex items-center gap-1 text-xs text-[var(--color-muted)]"><MapPin size={13}/>{report.address || 'Localização não informada'}</p></div><div className="flex gap-2 md:flex-col"><button onClick={() => handleAction(report.id, 'approve')} className="inline-flex min-h-9 flex-1 items-center justify-center gap-1.5 rounded-lg bg-[var(--color-success-tint)] px-3 text-xs font-bold text-[var(--color-success)]"><Check size={15}/> Aprovar</button><button onClick={() => handleAction(report.id, 'decline')} className="inline-flex min-h-9 flex-1 items-center justify-center gap-1.5 rounded-lg bg-[var(--color-danger-tint)] px-3 text-xs font-bold text-[var(--color-danger)]"><X size={15}/> Rejeitar</button></div></article>)}</div>}</main></Layout>;
}
